### ISSUE TITLE
Error in notebook

### ISSUE THREAD

**Issue by sdmorrey** [gabaid971/ts-forecaster#1]
There’s a gigantic error log in your notebook for prophet. It’s too long to post here, I don’t understand the error either unfortunately I just know it’s bigly long.

**Comment by gabaid971** [comment]
I only got gigantic DEBUG and INFO logs on the prophet side, but it's still working. If you got the same type of logs, you can just mask them. If not I'm curious to see them

**Comment by gabaid971** [comment]
i've cleaned some of the logs
