### ISSUE TITLE
The winner seem to be Prophet?

### ISSUE THREAD

**Issue by katopz** [gabaid971/ts-forecaster#2]
Refer to

> <img width="299" alt="image" src="https://github.com/gabaid971/ts-forecaster/assets/97060/923068bd-410d-4dc7-aca4-2b6ecdb9f979"> 
>
> So it seems that the best model, for this task, in this setup is TimesFM

But I see Prophet has a lower `RMSE` isn't it?
Just curious, sorry for nitpicking.

Thanks

**Comment by gabaid971** [comment]
You're totally right ! I tested it on multiple datasets and wrote this conclusion for another one ^^ will modify the conclusion

**Comment by katopz** [comment]
Cool, Thanks for your hard work, really want to see a comparison with `LightGBM` btw. :)

**Comment by gabaid971** [comment]
with pleasure :) yes when I have a bit of time I'll test lstm and gradient boosting
